export const MAX_OUTPUT_LENGTH = 450;
export const COMMAND_COOLDOWN = 15_000;

export const MODERATORS = [
	"AliDeAdam",
	"Cheese4Hire",
	"Evilton",
	"Jakkuii",
	"Jimester",
	"JohnKillah",
	"JohnnySquintz",
	"KERED_17",
	"LuckyReVamped",
	"McGibbles_",
	"PolarBear",
	"PsiKoticPersian",
	"ZaMM",
	"Zillla",
	"phiiiips",
	"tTriippy",
	"xVauda",
	"xduckbutter",
].join(", ");

export const REGULARS = [
	"AkinaSpeedStarWRX",
	"DeAngeloSr",
	"FlNDj",
	"FleshFurnace",
	"Gamercoco74",
	"GuiMinero",
	"JadedKudos",
	"KeijiMunox",
	"MsKenner",
	"Quikstop",
	"RoootyZ",
	"SalazarXionon",
	"TalnoyPrime",
	"TheCultCrow007",
	"TheNicoleVisser",
	"TheZenTryhard",
	"Toe_to_the_Knee",
	"Toyymaker",
	"TranquilityRuse",
	"TravassxPizza",
	"Valarky",
	"Voodoochild77",
	"Weeegie",
	"ZionZeta",
	"arminaterr",
	"bbaccararose",
	"carmellavender",
	"havok_RN",
	"iBlasstoise",
	"ltsDerpDiggler",
	"ltsIsMac",
	"ltsme_val",
	"omgitswabamy",
	"potatis_b",
	"rag2016xx",
	"somewhatbilal",
	"unfitmechanic67",
	"venom_music",
	"xiBread_",
].join(", ");
