export const MAX_OUTPUT_LENGTH = 450;
export const COMMAND_COOLDOWN = 15_000;

export const MODERATORS = [
	"AliDeAdam (male)",
	"Cheese4Hire",
	"Evilton",
	"Jakkuii",
	"Jimester",
	"JohnKillah",
	"JohnnySquintz",
	"KERED_17",
	"LuckyReVamped",
	"McGibbles_",
	"phiiiips",
	"PolarBear (female)",
	"PsiKoticPersian",
	"tTriippy",
	"xduckbutter",
	"xVauda",
	"ZaMM",
	"Zillla",
].join(", ");

export const REGULARS = [
	"AkinaSpeedStarWRX",
	"arminaterr",
	"bbaccararose (female)",
	"carmellavender (male)",
	"corvidsquill",
	"DeAngeloSr",
	"FleshFurnace",
	"FlNDj",
	"Gamercoco74",
	"GuiMinero",
	"havok_RN",
	"iBlasstoise",
	"JadedKudos",
	"KableKompany",
	"KeijiMuno",
	"ltsDerpDiggler",
	"ltsIsMac",
	"ltsme_val (female)",
	"Mari___Juana",
	"MsKenner (female)",
	"omgitswabamy",
	"potatis_b",
	"Quikstop",
	"rag2016xx",
	"RoootyZ",
	"SalazarXionon",
	"simpiydre",
	"somewhatbilal",
	"Spoontis",
	"TalnoyPrime",
	"TheCultCrow007",
	"TheNicoleVisser (female)",
	"TheZenTryhard",
	"Toe_to_the_Knee",
	"Toyymaker",
	"TranquilityRuse",
	"TravassxPizza",
	"unfitmechanic67",
	"Valarky (female)",
	"venom_music",
	"Voodoochild77",
	"warriorpt",
	"Weeegie",
	"xiBread_",
	"ZionZeta (female)",
].join(", ");
